# Depression and Marital Status
Study of 159 depression patients categorised by **level of
depression** (severe, moderate, mild), and **marital status** (single,
married, widowed/divorced).

| Depression | Single | Married | Divorced |
|------------|--------|---------|----------|
| Severe     | 16     | 22      | 19       |   
| Moderate   | 29     | 33      | 14       |   
| Mild       | 9      | 14      | 3        |  


**Question**: Does the conditional distribution of depression level change marital
status?

In [1]:
# Load some standard packages
import numpy as np
import pandas as pd
import statsmodels.api as sm
import scipy.stats as stats
import matplotlib.pyplot as plt

In [2]:
# Define a contingency table
observed = np.array([[16, 22, 19],[29, 33, 14],[9,14,3]])
print(observed)

[[16 22 19]
 [29 33 14]
 [ 9 14  3]]


In [3]:
# Compute chi2
chi2, p, dof, ex =stats.contingency.chi2_contingency(observed)
print(ex)

[[19.35849057 24.73584906 12.90566038]
 [25.81132075 32.98113208 17.20754717]
 [ 8.83018868 11.28301887  5.88679245]]


In [7]:
# Compute chi2 statistic
chi2, p, dof, ex = stats.contingency.chi2_contingency(observed)
print("chi2 stat")
print(np.round(chi2,2))

print("")

crit = stats.chi2.ppf(q = 0.9, df = 4)
print("Critical Value")
print(round(crit,2))

chi2 stat
6.83

Critical Value
7.78


**Conclusion**: Since chi2 stat < Critical Value, we conclude that no strong evidence exist to say that the level of depression is associated with marital status.